### ISSUE TITLE
Backend - Seal of X Information

### ISSUE THREAD

**Issue by Devsome** [Devsome/silkroad-laravel#49]
On the Backend Dashboard an Information Panel for how many **Seal Of X** items currently in the game.
When you click on the count number, some more Information about that Item.

- Item Code
- Owner
- First Owner
- Dropped Time
- Serial
- Icon

**Comment by Devsome** [comment]
Todo: Getting the Guild and Cos Inventory + if possible the dropped time and first owner

**Comment by Devsome** [comment]
![image](https://user-images.githubusercontent.com/10772980/85086161-203bd380-b1da-11ea-9419-2c96be8f8cb6.png)

Hovering to see the amount: \
![image](https://user-images.githubusercontent.com/10772980/85086191-2d58c280-b1da-11ea-854f-7d4846c4c0f5.png)

**Comment by EsteveLuis** [comment]
Good bro

**Comment by Devsome** [comment]
Hint from **boykoe** Items could also be in the WebInventory. 🔥

**Comment by Devsome** [comment]
Still need Guild and Cos Inventory
