### ISSUE TITLE
Payment Methods

### ISSUE THREAD

**Issue by Devsome** [Devsome/silkroad-laravel#66]
Adding selected payment methods. But offer these via package.

PayOp
PayPal
Paymentwall

**Comment by Devsome** [comment]
- PayOp - Needs to be tested with the IPN.
- PayPal - Currently being implemented
- Paymentwall - nothing

**Comment by SaifurRahmanMohsin** [comment]
Use [OmniPay](https://github.com/thephpleague/omnipay) and you should be able to implement all of them easily.

**Comment by Devsome** [comment]
I am using omnipay, but still for PayOp for example you need a verified Account. They do not support a Sandbox
