### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Devsome** [Devsome/silkroad-laravel#77]
You only need to translate the `auth`& normal files. The `backend` folder is not mandatory.

1. Fork this project
2. git clone your forked project
3. Create a new folder called `YOURLANGUAGE IN ISO CODE` in https://github.com/Devsome/silkroad-laravel/tree/master/resources/lang
4. Replace all the normal strings not the keys with the right language
6. When you find some placeholders like (many more), do not replace them.
```
You have successfully bold ":name" for :gold Gold
```
7. Make a git commit + git push
8. Create a Pull Request

There are also one part with `// do not change this`, Please do not change what is underneath.

If you have any questions just ask.

**Comment by helara** [comment]
Hello! I would like to help you with the Spanish translation.

**Comment by Devsome** [comment]
@helara sure, do you need any kind of help?

**Comment by helara** [comment]
> @helara sure, do you need any kind of help?

Not right now, but I'll let you know if I need it. Working on it!

**Comment by MauSant** [comment]
Hi I would like to help with Portuguese Brazil Translation! 
Are you participating on the hacktoberfest? I did not see the Label on the repository
I am new at laravel could you help me which files should be translated?
